### ISSUE TITLE
About Consensus-driven Fusion module

### ISSUE THREAD

**Issue by DayDayUpUpUp666** [hongfz16/DS-Net#13]
Hi, thanks for your great work. I wonder to know that how the Consensus-driven Fusion module implementing？I found the merge_ins_sem in common_utils. But I donot find how to use the 'merge_ins_sem' in other code.

**Comment by hongfz16** [comment]
Hi. Thank you for your interest. Yes the consensus-driven fusion is implemented in the `merge_ins_sem` function in `common_utils`. And it is called in this line: https://github.com/hongfz16/DS-Net/blob/72c3c251dd57074c3ce30a489fb47710a9fb5c1a/network/model_zoo.py#L348.

If you wish to use this module in your code, I think it is quite easy to implement it yourself. You travel through all segmented instances. For each one of them, you perform a majority voting in terms of semantic labels for all the points of the instance. The idea is to unify the semantic labels inside each instance. If you have further questions, feel free to reopen it or add another post.
