### ISSUE TITLE
Exact formula to get weights for weighted cross-entropy loss

### ISSUE THREAD

**Issue by hskim617** [hongfz16/DS-Net#17]
Hi, in network/model_zoo.py, there are weights for weighted cross-entropy loss(in PolarSpconv class). Could you tell me the exact formula to get each weight in the cross-entropy loss?

**Comment by yuyang-cloud** [comment]
@hskim617  Hi, I would also like to know the formula to get each weight in the cross-entropy loss, could please share how do you understand? Thanks!
