### ISSUE TITLE
About ins_labels

### ISSUE THREAD

**Issue by January-cv** [hongfz16/DS-Net#4]
Thank you open you code!

dataloader -> dataset.py line 79:
"ins_labels = annotated_data" should be changed to "ins_labels = annotated_data >> 16"?

**Comment by hongfz16** [comment]
Thanks for the question.

No. You should not change that. If I remember it correctly, the definition of instance label is `semantic label + id`. The `id` is counted from zero for each semantic classes.

Therefore, if you change to `annotated_data >> 16`, there is chance that in the same scene two different instances with different semantic classes share same `ins_label`.

You can check that easily by yourself. Correct me if I am wrong. Thanks a lot.
