### ISSUE TITLE
About the inference time

### ISSUE THREAD

**Issue by zhanghming** [hongfz16/DS-Net#5]
Hi, thanks for your sharing what's an amazing work in lidar panoptic segmentation field. 

I wonder what the exact inference time in Sementic KITTI dataset and nuScenes dataset?

**Comment by hongfz16** [comment]
Thanks for your interest. The average inference time in SemKITTI validation set is 537.06ms/frame. The average inference time in nuScenes validation set is 264.80ms/frame. The detailed time analysis of each module will be listed in the camera-ready version of our paper.
