### ISSUE TITLE
shuffle makes no sense

### ISSUE THREAD

**Issue by zhixiongzh** [hongfz16/DS-Net#7]
Hi,
in the file function voxelize_spconv, which is in model_zoom.py, you shuffle all points by
`cat_pt_ind = cat_pt_ind[shuffled_ind,:]`

and then the output unq and processed_pooled_data is still in the order of the grid, which is done automatically by scatter_max function.
` pooled_data = torch_scatter.scatter_max(processed_cat_pt_fea, unq_inv, dim=0)[0]`

It seems this step makes no point in the function.

Usually, we shuffle the data in the dataloader, which has been done automatically, instead of shuffle the date within the batch.

**Comment by hongfz16** [comment]
Hi,

Thanks for the question.

Actually, the shuffling operation here is preparing the data for the random sampling in this [line](https://github.com/hongfz16/DS-Net/blob/main/network/model_zoo.py#L175). If we do not perform shuffling, then the sampling will not be random.

As for the scatter operation later, it has no relationship with the shuffling operation above. The above shuffling is done at the point level. Later the randomly sampled points will be converted to voxel by scatter operation.

If you have further confusion, feel free to continue this discussion.
