### ISSUE TITLE
mIoU much better using same semantics method

### ISSUE THREAD

**Issue by zhixiongzh** [hongfz16/DS-Net#8]
Sorry, it is not an issue but my personal confusion.
In the paper, Table 3, your method outperforms much better in mIoU even you use the same semantics segmentation head Cylinder3D.

Is the Cylinder3D only used as a backbone to get the feature and then you design(or modify) your own model to do the later semantics segmentation?

**Comment by hongfz16** [comment]
Sorry for the late reply. The decrease of the mIoU is because of the wrong prediction of the detection methods. The fusion strategy used here will respect the detection results even if it might make some of the right Cylinder3D predictions wrong.

**Comment by zhixiongzh** [comment]
> Sorry for the late reply. The decrease of the mIoU is because of the wrong prediction of the detection methods. The fusion strategy used here will respect the detection results even if it might make some of the right Cylinder3D predictions wrong.

Ok, that makes sense. 
So the Cylinder3D in DS-Net is the same as the original one, right?

**Comment by hongfz16** [comment]
Yes. The semantic segmentation part of DS-Net is the same as Cylinder3D.

**Comment by zhixiongzh** [comment]
Got it! I would close this.
